name: Deploy React App
on: workflow_dispatch
jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Get the reposutory code
        uses: actions/checkout@v4
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: cache deps
        uses: actions/cache@v3
        with:
          path: frontend/front-end/.npm
          key: node-modules-deps${{ hashFiles('**/package-lock.json') }}
        
      - name: Install dependecies
        run: npm ci
        working-directory: frontend/front-end
      - name: build frontend
        run: CI=false npm run build
        working-directory: frontend/front-end
      - name: deploy
        run: echo Deploying ...

  
      
      
