name: Deploy React App
on: push
jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Get the reposutory code
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm install
        working-directory: frontend/front-end
      - name: build frontend
        run: npm run build
        working-directory: frontend/front-end
      - name: deploy
        run: echo Deploying ...

  
      
      
