name: Test React App
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the reposutory code
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
        working-directory: frontend/front-end
      - name: Test applications
        run: npm run test
        working-directory: frontend/front-end
      
      
